# Generated by Django 2.2 on 2020-12-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20201227_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Expertise', 'verbose_name_plural': 'Expertises'},
        ),
    ]
