# Generated by Django 2.2 on 2020-12-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20201227_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
