# Generated by Django 2.2 on 2020-12-27 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20201227_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(error_messages={'min_length': 'not enough lengh'}, max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=4)]),
        ),
    ]
