# Generated by Django 2.2 on 2020-12-27 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_auto_20201227_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_min',
            field=models.IntegerField(error_messages={'min_value': 'dawdada'}, null=True, validators=[django.core.validators.MinValueValidator(limit_value=3)]),
        ),
    ]
