# Generated by Django 2.2 on 2021-01-20 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_auto_20201227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='salary_min',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=3, message='adasdawd')]),
        ),
    ]
