# Generated by Django 2.2 on 2021-01-26 08:04

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finder', '0010_auto_20210126_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
                ('root_folder', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='finder.Items')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
            bases=(projects.models.Override, models.Model),
        ),
    ]
