# Generated by Django 2.2 on 2021-01-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_root', models.BooleanField(default=False, editable=False)),
                ('type', models.CharField(choices=[('FILE', 'FILE'), ('FOLDER', 'FOLDER')], max_length=50)),
                ('content_items', models.ManyToManyField(blank=True, related_name='_items_content_items_+', to='finder.Items')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finder.Items')),
            ],
            options={
                'verbose_name': 'Files and folders',
                'verbose_name_plural': 'Files and folders',
            },
        ),
    ]
