# Generated by Django 2.2 on 2021-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20210110_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Files and Folders', 'verbose_name_plural': 'Files and Folders'},
        ),
        migrations.AlterField(
            model_name='items',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
