# Generated by Django 2.2 on 2021-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20210110_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='content_items',
            field=models.ManyToManyField(blank=True, related_name='_items_content_items_+', to='finder.Items'),
        ),
    ]
