# Generated by Django 2.2 on 2021-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_auto_20210110_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='content_items',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Items'),
        ),
    ]
