# Generated by Django 2.2 on 2021-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_auto_20210126_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
