# Generated by Django 2.2 on 2021-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_items_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='content_items',
            field=models.ManyToManyField(blank=True, to='finder.Items'),
        ),
    ]
